# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/thomas-mauran"

[social.params]
icon = "brand-github"

[[social]]
identifier = "email"
name = "Mail"
url = "mailto:thomas.mauran@etu.umontpellier.fr"

[social.params]
icon = "mail"
